### ISSUE TITLE
Duplicate scans in Stanford Fullysampled 3D FSE Knees

### ISSUE THREAD

**Issue by batuozt** [mikgroup/mridata#24]
Hi all,

We have been using the Stanford Fullysampled 3D FSE Knees Dataset for a MR reconstruction project, and have come across an issue where samples corresponding to UUID's `2588bfa8-0c97-478c-aa5a-487cc88a590d` and `b7d435a1-2421-48d2-946c-d1b3372f7c60` correspond to the exact same dataset, i.e. the k-space data for both UUID's were the same. This was verified by calculating norm between the two raw k-space data and by inspecting the data before any pre-processing as shown in the following simple code to reproduce the issue:

`import ismrmd`
`import h5py`
`i = 8192`
`dset1 = ismrmrd.Dataset('/directory/2588bfa8-0c97-478c-aa5a-487cc88a590d', 'dataset', create_if_needed=False)`
`dset2 = ismrmrd.Dataset('/directory/b7d435a1-2421-48d2-946c-d1b3372f7c60', 'dataset', create_if_needed=False)`
`data1 = dset1._file['dataset']`
`img1 = np.array(data1['data'])`
`mean1 = np.mean(img1[i][2])`
`data2 = dset2._file['dataset']`
`img2 = np.array(data2['data'])`
`mean2 = np.mean(img2[i][2])`

where i is a random index from [0:81920] that is selected to further verify that k-space data are identical for both UUID's. mean1 and mean2 turn out to be the same regardless of the selected 'i'. Could you please address this issue? 

Thanks for your time!

**Comment by Mon-ius** [comment]
Hi, do you know how to install ismrmd for python? I tried to compile it from source https://github.com/ismrmrd/ismrmrd and install https://github.com/ismrmrd/ismrmrd-python-tools. But didn't get it work.

**Comment by frankong** [comment]
Thanks for bringing this up. I've deleted b7d435a1-2421-48d2-946c-d1b3372f7c60.
